using System.Windows.Controls;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using Hardcodet.Wpf.TaskbarNotification;
using DMShot.Localization;
namespace DMShot.Platform;

public sealed class NotifyIconTray : ITrayIcon
{
    private readonly TaskbarIcon _icon;
    public event Action? OpenRequested;
    public event Action? FullScreenRequested;
    public event Action? AreaRequested;
    public event Action? VideoFullRequested;
    public event Action? VideoAreaRequested;
    public event Action? SettingsRequested;
    public event Action? QuitRequested;

    public NotifyIconTray()
    {
        _icon = new TaskbarIcon
        {
            ToolTipText = Loc.Instance["trayTooltip"],
            IconSource = LoadIcon()
        };
        BuildMenu();
        _icon.TrayMouseDoubleClick += (_, _) => OpenRequested?.Invoke();
        Loc.Instance.LanguageChanged += BuildMenu;
    }

    // Effective hotkeys shown as menu hints (mac parity: updateMenuTitles).
    private string? _hintFull, _hintArea, _hintVideoFull, _hintVideoArea;

    public void SetHotkeyHints(string full, string area, string videoFull, string videoArea)
    {
        _hintFull = full; _hintArea = area; _hintVideoFull = videoFull; _hintVideoArea = videoArea;
        BuildMenu();
    }

    private static string WithHint(string title, string? hint)
        => string.IsNullOrEmpty(hint) ? title : $"{title}  ({hint})";

    // Rebuilt on language change so the tray menu follows the active language.
    private void BuildMenu()
    {
        var menu = new ContextMenu { Style = MenuStyle };
        menu.Resources.Add(typeof(MenuItem), MenuItemStyle);
        // A Separator inside a menu is styled via MenuItem.SeparatorStyleKey, NOT typeof(Separator)
        // — keying it wrong left the OS default (a bright white line) showing on the dark menu.
        menu.Resources.Add(MenuItem.SeparatorStyleKey, SeparatorStyle);
        menu.Items.Add(Item(WithHint(Loc.Instance["menuNewFullScreen"], _hintFull), () => FullScreenRequested?.Invoke()));
        menu.Items.Add(Item(WithHint(Loc.Instance["menuNewSelection"], _hintArea), () => AreaRequested?.Invoke()));
        menu.Items.Add(Item(WithHint(Loc.Instance["menuNewVideoFull"], _hintVideoFull), () => VideoFullRequested?.Invoke()));
        menu.Items.Add(Item(WithHint(Loc.Instance["menuNewVideoArea"], _hintVideoArea), () => VideoAreaRequested?.Invoke()));
        menu.Items.Add(new Separator());
        menu.Items.Add(Item(Loc.Instance["menuOpenWindow"], () => OpenRequested?.Invoke()));
        menu.Items.Add(Item(Loc.Instance["menuSettings"], () => SettingsRequested?.Invoke()));
        menu.Items.Add(new Separator());
        menu.Items.Add(Item(Loc.Instance["menuQuit"], () => QuitRequested?.Invoke()));
        _icon.ContextMenu = menu;
    }

    // Windows tray icons are full-color, so the tray uses a dark squircle + white camera
    // (the app-icon look, but WITHOUT the viewfinder corner brackets so it stays legible at
    // 16-24px) — generated by windows/tools/make-tray-icon.ps1. (macOS differs: its menu bar
    // wants a monochrome template symbol, handled on that side.) Falls back to a generated
    // dark squircle + white square if the bundled .ico is missing.
    private static ImageSource LoadIcon()
    {
        try
        {
            return new BitmapImage(new Uri("pack://application:,,,/Resources/TrayIcon.ico"));
        }
        catch
        {
            var rtb = new RenderTargetBitmap(32, 32, 96, 96, PixelFormats.Pbgra32);
            var dv = new DrawingVisual();
            using (var dc = dv.RenderOpen())
            {
                dc.DrawRoundedRectangle(new SolidColorBrush(Color.FromRgb(0x16, 0x16, 0x1c)), null,
                    new System.Windows.Rect(0, 0, 32, 32), 7, 7);
                dc.DrawRectangle(new SolidColorBrush(Colors.White), null,
                    new System.Windows.Rect(9, 11, 14, 11));
            }
            rtb.Render(dv);
            rtb.Freeze();
            return rtb;
        }
    }

    private static MenuItem Item(string header, Action onClick)
    { var m = new MenuItem { Header = header }; m.Click += (_, _) => onClick(); return m; }

    // ===== Dark context-menu styling (the default WPF menu rendered dark text on the
    // OS dark menu background — unreadable). Dark surface + light text + dark hover. =====

    private static System.Windows.Style St(string xaml) => (System.Windows.Style)XamlReader.Parse(xaml);

    private static readonly System.Windows.Style MenuStyle = St(
@"<Style xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation' xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml' TargetType='ContextMenu'>
  <Setter Property='Foreground' Value='#E8E8EA'/><Setter Property='FontSize' Value='13'/>
  <Setter Property='Template'><Setter.Value>
    <ControlTemplate TargetType='ContextMenu'>
      <Border Background='#1E1E22' BorderBrush='#3A3A42' BorderThickness='1' CornerRadius='8' Padding='3'>
        <ItemsPresenter/>
      </Border>
    </ControlTemplate>
  </Setter.Value></Setter>
</Style>");

    private static readonly System.Windows.Style MenuItemStyle = St(
@"<Style xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation' xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml' TargetType='MenuItem'>
  <Setter Property='Foreground' Value='#E8E8EA'/>
  <Setter Property='Template'><Setter.Value>
    <ControlTemplate TargetType='MenuItem'>
      <Border x:Name='b' Background='Transparent' CornerRadius='5' Padding='12,6' Margin='2,1'>
        <ContentPresenter ContentSource='Header' RecognizesAccessKey='True' VerticalAlignment='Center'/>
      </Border>
      <ControlTemplate.Triggers>
        <Trigger Property='IsHighlighted' Value='True'><Setter TargetName='b' Property='Background' Value='#3A3A42'/></Trigger>
        <Trigger Property='IsEnabled' Value='False'><Setter Property='Foreground' Value='#6A6A70'/></Trigger>
      </ControlTemplate.Triggers>
    </ControlTemplate>
  </Setter.Value></Setter>
</Style>");

    private static readonly System.Windows.Style SeparatorStyle = St(
@"<Style xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation' xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml' TargetType='Separator'>
  <Setter Property='Template'><Setter.Value>
    <ControlTemplate TargetType='Separator'>
      <Border Height='1' Background='#2E2E35' Margin='8,4'/>
    </ControlTemplate>
  </Setter.Value></Setter>
</Style>");

    public void Show() => _icon.Visibility = System.Windows.Visibility.Visible;
    public void Dispose() { Loc.Instance.LanguageChanged -= BuildMenu; _icon.Dispose(); }
}
