using System.Collections.Generic;
using System.ComponentModel;

namespace DMShot.Localization;

/// <summary>
/// Central, observable string provider. XAML binds to the indexer via the
/// {loc:Tr Key} markup extension; code-behind reads Loc.Instance[key] and rebuilds
/// on the LanguageChanged event. The En/De tables must keep identical key sets —
/// the LocTests parity test enforces it.
/// </summary>
public sealed class Loc : INotifyPropertyChanged
{
    public static Loc Instance { get; } = new();

    public event PropertyChangedEventHandler? PropertyChanged;
    public event Action? LanguageChanged;

    private Language _current = Language.English;
    public Language Current
    {
        get => _current;
        set
        {
            if (_current == value) return;
            _current = value;
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item[]"));
            LanguageChanged?.Invoke();
        }
    }

    public string this[string key]
    {
        get
        {
            var table = _current == Language.German ? De : En;
            return table.TryGetValue(key, out var v) ? v
                 : (En.TryGetValue(key, out var f) ? f : key);
        }
    }

    public static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>
    {
        ["sidebarWidth"] = "Sidebar width",
        ["gradientWarm"] = "Warm gradient",
        ["gradientCool"] = "Cool gradient",
        ["gradientNeutral"] = "Neutral gradient",
        ["moreTools"] = "More tools",
        ["emptyCanvasTitle"] = "Create a capture",
        ["emptyCanvasHint"] = "Choose a capture action or use its shortcut.",
        ["openImage"] = "Open Image…",
        ["pasteImage"] = "Paste",
        ["openImageFilter"] = "PNG or JPEG image|*.png;*.jpg;*.jpeg",
        ["importFailedTitle"] = "Could not import image",
        ["importFailedBody"] = "The image could not be imported:\n{0}",
        ["importTooLarge"] = "The image exceeds the 100 MiB or 40-megapixel limit.",
        ["importInvalid"] = "Choose a valid PNG or JPEG image.",
        ["importOneImage"] = "Drop one PNG or JPEG image at a time.",
        ["settingsTitle"] = "Settings",
        ["sectionGeneral"] = "General",
        ["sectionShortcuts"] = "Shortcuts",
        ["sectionLanguage"] = "Language",
        ["sectionUpdates"] = "Updates",
        ["launchAtLogin"] = "Launch at login",
        ["launchAtLoginHelp"] = "Start DM Screenshot automatically when you log in.",
        ["showLoupe"] = "Zoom loupe",
        ["showLoupeHelp"] = "Show a magnifier while selecting an area, for pixel-precise edges.",
        ["afterCapture"] = "After capture",
        ["afterCaptureHelp"] = "What happens right after a screenshot is taken.",
        ["afterCaptureMainWindow"] = "Open main window",
        ["afterCaptureQuickEdit"] = "Show Quick-Edit bar",
        ["design"] = "Design",
        ["designHelp"] = "Choose the visual style for DM Screenshot.",
        ["designGraphiteSand"] = "Graphite Sand",
        ["designStandard"] = "Standard Design",
        ["designBlack"] = "Black Utility",
        ["languageLabel"] = "Language",
        ["languageHelp"] = "Interface language.",
        ["version"] = "Version",
        ["versionHelp"] = "Installed version.",
        ["checkForUpdates"] = "Check for Updates",
        ["updatesDisabled"] = "Automatic updates work in the installed version of DM Screenshot.",
        ["checkingForUpdates"] = "Checking for updates…",
        ["upToDate"] = "You’re up to date.",
        ["updateAvailable"] = "Version {0} is available.",
        ["downloadInstall"] = "Download & Install",
        ["later"] = "Later",
        ["downloading"] = "Downloading… {0}%",
        ["readyToInstall"] = "Version {0} is ready to install.",
        ["restartInstall"] = "Restart & Install",
        // Active update prompt (spec 2026-08-02)
        ["updateReadyTitle"] = "Update ready",
        ["updateReadyMessage"] = "DM Screenshot {0} has been downloaded.",
        ["tryAgain"] = "Try Again",
        ["whatsNewIn"] = "What’s new in {0}",
        ["actionFullScreen"] = "Full screen",
        ["actionAreaSelection"] = "Area selection",
        ["actionVideoFull"] = "Record full screen",
        ["actionVideoArea"] = "Record area",
        ["shortcutsHint"] = "Click a field and press the new key combination.",
        ["systemInUse"] = "This combination is already in use by the system.",
        ["needsModifier"] = "Use at least one modifier (Ctrl, Alt, Shift or Win).",
        ["alreadyUsedBy"] = "Already used by “{0}”.",
        ["resetToDefaults"] = "Reset to defaults",
        ["menuNewFullScreen"] = "New Full Screen",
        ["menuNewSelection"] = "New Selection",
        ["menuNewVideoFull"] = "New Video (Full Screen)",
        ["menuNewVideoArea"] = "New Video (Selection)",
        ["menuOpenWindow"] = "Open Window",
        ["menuSettings"] = "Settings…",
        ["menuQuit"] = "Quit",
        ["copy"] = "Copy",
        ["save"] = "Save",
        ["saveEllipsis"] = "Save…",
        ["stop"] = "Stop",
        ["discard"] = "Discard",
        ["close"] = "Close",
        ["createGif"] = "Create GIF",
        ["creatingGif"] = "Creating GIF…",
        ["menuUpdateAvailable"] = "Update to {0} available…",
        ["gifQualityStandard"] = "Standard",
        ["gifQualitySmall"] = "Small",
        ["gifConvertToSmall"] = "Convert to Small",
        ["gifPreviewTitle"] = "DM Screenshot — GIF",
        ["gifReady"] = "GIF ready",
        ["gifDecoding"] = "Preparing preview…",
        ["previewCreateTitle"] = "Preview & Trim",
        ["duration"] = "Duration",
        ["estimatedGifSize"] = "Estimated GIF size: {0}",
        ["videoPlayhead"] = "Play",
        ["videoTrimIn"] = "Start",
        ["videoTrimOut"] = "End",
        ["resetZoomToFit"] = "Reset zoom to fit",
        ["videoUnsupportedMessage"] = "Video capture requires Windows 10 version 1803 or newer.",
        ["videoStartFailedMessage"] = "Could not start recording on this display.",
        ["saveDialogPngFilter"] = "PNG image|*.png",
        ["saveDialogGifFilter"] = "GIF image (*.gif)|*.gif",
        ["saveFailedTitle"] = "Could not save",
        ["captureNoDisplaysMessage"] = "No displays are available.",
        ["quitUnsavedMessage"] = "Some changes could not be saved to history. Quit without saving them? Choose No to keep editing or save the image elsewhere.",
        ["operationFailedTitle"] = "Action failed",
        ["captureFailedMessage"] = "Capture failed. Please try again.\n\n{0}",
        ["clipboardFailedMessage"] = "Could not copy to the clipboard. Your capture is still available; please try Copy again.\n\n{0}",
        ["historyWriteFailedMessage"] = "Could not save changes to history. Please save the image before closing.\n\n{0}",
        ["historyWriteFailedDetail"] = "The history folder could not be written.",
        ["saveFailedMessage"] = "The file could not be written:\n{0}",
        ["restartFailedMessage"] = "The update could not restart the app:\n{0}",
        ["gifFailedMessage"] = "The GIF could not be created:\n{0}",
        ["shortcutRecorderPrompt"] = "Click and press keys…",
        ["quickEditSizeBlur"] = "Size / blur strength",
        ["quickEditEditInMain"] = "Edit in main window",
        ["undo"] = "Undo",
        ["redo"] = "Redo",
        ["editorFullScreen"] = "Full Screen",
        ["editorSelection"] = "Selection",
        ["editorVideoFull"] = "Record Screen",
        ["editorVideoArea"] = "Record Area",
        ["historyHeader"] = "HISTORY",
        ["historyImageIdentity"] = "Screenshot · {0}",
        ["historyVideoIdentity"] = "GIF · {0}",
        ["settings"] = "Settings",
        ["deleteCapture"] = "Delete this capture",
        ["toolSelect"] = "Select / Move",
        ["toolArrow"] = "Arrow",
        ["toolRect"] = "Rectangle",
        ["toolEllipse"] = "Ellipse",
        ["toolUnderline"] = "Underline",
        ["toolHighlighter"] = "Highlighter",
        ["toolStep"] = "Numbered step",
        ["toolText"] = "Text",
        ["toolBlur"] = "Blur / Pixelate",
        ["toolCrop"] = "Crop",
        ["color"] = "Color",
        ["blur"] = "Blur",
        ["size"] = "Size",
        ["hex"] = "Hex",
        ["ok"] = "OK",
        ["cancel"] = "Cancel",
        ["trayTooltip"] = "DM Screenshot",
        ["firstRunTitle"] = "DM Screenshot installed",
        ["firstRunMessage"] = "The app is ready and runs in the system tray. Take screenshots via the tray menu or the keyboard shortcuts.",
        // Frame / pretty-background presets (Task 12 — mirror of mac/Sources/DMShot/Localization.swift)
        ["background"] = "Background",
        ["bgPadding"] = "Padding",
        ["bgCorners"] = "Corners",
        ["bgFill"] = "Fill",
        ["bgPadSmall"] = "Small",
        ["bgPadMedium"] = "Medium",
        ["bgPadLarge"] = "Large",
        ["bgCornerNone"] = "None",
        ["bgCornerSoft"] = "Soft",
        ["bgCornerRound"] = "Round",
        ["bgBlur"] = "Blur",
        // History limit + batch save
        ["batchSaveHistoryFailed"] = "Save the latest changes to history successfully before exporting the selection.",
        ["historyLimit"] = "History limit",
        ["historyLimitHelp"] = "How many captures the history keeps. Older ones are removed automatically.",
        ["historyUnlimited"] = "Unlimited",
        ["defaultSaveFolder"] = "Default save folder",
        ["defaultSaveFolderHelp"] = "Where captures are saved. If none is set, DM Screenshot asks once and suggests Pictures\\Screenshots.",
        ["chooseFolder"] = "Choose Folder…",
        ["folderNotSet"] = "Not set",
        ["selectForBatchSave"] = "Select for saving",
        ["saveSelected"] = "Save selection ({0})",
        ["clearSelection"] = "Clear selection",
        ["batchSaveFolderTitle"] = "Choose a folder for the selected captures",
        ["batchSaveDoneTitle"] = "Saved",
        ["batchSaveDone"] = "{0} captures saved to:\n{1}",
        ["batchSavePartial"] = "{0} of {1} captures could not be saved.",
    };

    public static readonly IReadOnlyDictionary<string, string> De = new Dictionary<string, string>
    {
        ["sidebarWidth"] = "Seitenleistenbreite",
        ["gradientWarm"] = "Warmer Verlauf",
        ["gradientCool"] = "Kühler Verlauf",
        ["gradientNeutral"] = "Neutraler Verlauf",
        ["moreTools"] = "Mehr Werkzeuge",
        ["emptyCanvasTitle"] = "Aufnahme erstellen",
        ["emptyCanvasHint"] = "Wähle eine Aufnahme oder nutze den Kurzbefehl.",
        ["openImage"] = "Bild öffnen…",
        ["pasteImage"] = "Einfügen",
        ["openImageFilter"] = "PNG- oder JPEG-Bild|*.png;*.jpg;*.jpeg",
        ["importFailedTitle"] = "Bild konnte nicht importiert werden",
        ["importFailedBody"] = "Das Bild konnte nicht importiert werden:\n{0}",
        ["importTooLarge"] = "Das Bild überschreitet die Grenze von 100 MiB oder 40 Megapixeln.",
        ["importInvalid"] = "Wähle ein gültiges PNG- oder JPEG-Bild.",
        ["importOneImage"] = "Lege jeweils nur ein PNG- oder JPEG-Bild ab.",
        ["settingsTitle"] = "Einstellungen",
        ["sectionGeneral"] = "Allgemein",
        ["sectionShortcuts"] = "Kurzbefehle",
        ["sectionLanguage"] = "Sprache",
        ["sectionUpdates"] = "Updates",
        ["launchAtLogin"] = "Beim Anmelden starten",
        ["launchAtLoginHelp"] = "DM Screenshot automatisch beim Anmelden starten.",
        ["showLoupe"] = "Zoom-Lupe",
        ["showLoupeHelp"] = "Beim Auswählen eines Bereichs eine Lupe für pixelgenaue Kanten anzeigen.",
        ["afterCapture"] = "Nach der Aufnahme",
        ["afterCaptureHelp"] = "Was direkt nach einem Screenshot passiert.",
        ["afterCaptureMainWindow"] = "Hauptfenster öffnen",
        ["afterCaptureQuickEdit"] = "Schnellbearbeitungsleiste anzeigen",
        ["design"] = "Gestaltung",
        ["designHelp"] = "Wähle den visuellen Stil für DM Screenshot.",
        ["designGraphiteSand"] = "Graphite Sand",
        ["designStandard"] = "Standard-Design",
        ["designBlack"] = "Black-Utility-Design",
        ["languageLabel"] = "Sprache",
        ["languageHelp"] = "Sprache der Oberfläche.",
        ["version"] = "Version",
        ["versionHelp"] = "Installierte Version.",
        ["checkForUpdates"] = "Nach Updates suchen",
        ["updatesDisabled"] = "Automatische Updates funktionieren in der installierten Version von DM Screenshot.",
        ["checkingForUpdates"] = "Suche nach Updates…",
        ["upToDate"] = "Du bist auf dem neuesten Stand.",
        ["updateAvailable"] = "Version {0} ist verfügbar.",
        ["downloadInstall"] = "Herunterladen & installieren",
        ["later"] = "Später",
        ["downloading"] = "Lädt… {0} %",
        ["readyToInstall"] = "Version {0} ist installationsbereit.",
        ["restartInstall"] = "Neu starten & installieren",
        // Active update prompt (spec 2026-08-02)
        ["updateReadyTitle"] = "Update bereit",
        ["updateReadyMessage"] = "DM Screenshot {0} wurde heruntergeladen.",
        ["tryAgain"] = "Erneut versuchen",
        ["whatsNewIn"] = "Neu in {0}",
        ["actionFullScreen"] = "Vollbild",
        ["actionAreaSelection"] = "Bereichsauswahl",
        ["actionVideoFull"] = "Vollbild aufnehmen",
        ["actionVideoArea"] = "Bereich aufnehmen",
        ["shortcutsHint"] = "Auf ein Feld klicken und die neue Tastenkombination drücken.",
        ["systemInUse"] = "Diese Kombination wird bereits vom System verwendet.",
        ["needsModifier"] = "Mindestens eine Modifizierertaste verwenden (Strg, Alt, Umschalt oder Win).",
        ["alreadyUsedBy"] = "Bereits belegt von „{0}“.",
        ["resetToDefaults"] = "Auf Standard zurücksetzen",
        ["menuNewVideoFull"] = "Neues Video (Vollbild)",
        ["menuNewVideoArea"] = "Neues Video (Auswahl)",
        ["menuNewFullScreen"] = "Neuer Vollbild-Screenshot",
        ["menuNewSelection"] = "Neue Auswahl",
        ["menuOpenWindow"] = "Editor öffnen",
        ["menuSettings"] = "Einstellungen…",
        ["menuQuit"] = "Beenden",
        ["copy"] = "Kopieren",
        ["save"] = "Speichern",
        ["saveEllipsis"] = "Speichern…",
        ["stop"] = "Stopp",
        ["discard"] = "Verwerfen",
        ["close"] = "Schließen",
        ["createGif"] = "GIF erstellen",
        ["creatingGif"] = "GIF wird erstellt…",
        ["menuUpdateAvailable"] = "Update auf {0} verfügbar…",
        ["gifQualityStandard"] = "Standard",
        ["gifQualitySmall"] = "Klein",
        ["gifConvertToSmall"] = "In Klein umwandeln",
        ["gifPreviewTitle"] = "DM Screenshot — GIF",
        ["gifReady"] = "GIF bereit",
        ["gifDecoding"] = "Vorschau wird vorbereitet…",
        ["previewCreateTitle"] = "Vorschau & Zuschneiden",
        ["duration"] = "Dauer",
        ["estimatedGifSize"] = "Geschätzte GIF-Größe: {0}",
        ["videoPlayhead"] = "Wiedergabe",
        ["videoTrimIn"] = "Start",
        ["videoTrimOut"] = "Ende",
        ["resetZoomToFit"] = "Zoom auf Fenstergröße zurücksetzen",
        ["videoUnsupportedMessage"] = "Videoaufnahme erfordert Windows 10 Version 1803 oder neuer.",
        ["videoStartFailedMessage"] = "Aufnahme auf diesem Display konnte nicht gestartet werden.",
        ["saveDialogPngFilter"] = "PNG-Bild|*.png",
        ["saveDialogGifFilter"] = "GIF-Bild (*.gif)|*.gif",
        ["saveFailedTitle"] = "Speichern fehlgeschlagen",
        ["captureNoDisplaysMessage"] = "Es sind keine Bildschirme verfügbar.",
        ["quitUnsavedMessage"] = "Einige Änderungen konnten nicht im Verlauf gespeichert werden. Trotzdem beenden und diese Änderungen verwerfen? Wähle Nein, um weiterzubearbeiten oder das Bild an anderer Stelle zu speichern.",
        ["operationFailedTitle"] = "Aktion fehlgeschlagen",
        ["captureFailedMessage"] = "Aufnahme fehlgeschlagen. Bitte erneut versuchen.\n\n{0}",
        ["clipboardFailedMessage"] = "Kopieren in die Zwischenablage fehlgeschlagen. Die Aufnahme ist weiterhin verfügbar; bitte erneut kopieren.\n\n{0}",
        ["historyWriteFailedMessage"] = "Änderungen konnten nicht im Verlauf gespeichert werden. Bitte das Bild vor dem Schließen speichern.\n\n{0}",
        ["historyWriteFailedDetail"] = "Der Verlaufsordner konnte nicht beschrieben werden.",
        ["saveFailedMessage"] = "Die Datei konnte nicht geschrieben werden:\n{0}",
        ["restartFailedMessage"] = "Das Update konnte die App nicht neu starten:\n{0}",
        ["gifFailedMessage"] = "Das GIF konnte nicht erstellt werden:\n{0}",
        ["shortcutRecorderPrompt"] = "Klicken und Tastenkombination drücken…",
        ["quickEditSizeBlur"] = "Größe / Weichzeichnerstärke",
        ["quickEditEditInMain"] = "Im Hauptfenster bearbeiten",
        ["undo"] = "Rückgängig",
        ["redo"] = "Wiederholen",
        ["editorFullScreen"] = "Vollbild",
        ["editorSelection"] = "Auswahl",
        ["editorVideoFull"] = "Bildschirm aufnehmen",
        ["editorVideoArea"] = "Bereich aufnehmen",
        ["historyHeader"] = "VERLAUF",
        ["historyImageIdentity"] = "Bildschirmfoto · {0}",
        ["historyVideoIdentity"] = "GIF · {0}",
        ["settings"] = "Einstellungen",
        ["deleteCapture"] = "Diese Aufnahme löschen",
        ["toolSelect"] = "Auswählen / Bewegen",
        ["toolArrow"] = "Pfeil",
        ["toolRect"] = "Rechteck",
        ["toolEllipse"] = "Ellipse",
        ["toolUnderline"] = "Unterstreichen",
        ["toolHighlighter"] = "Textmarker",
        ["toolStep"] = "Nummerierter Schritt",
        ["toolText"] = "Text",
        ["toolBlur"] = "Weichzeichnen / Verpixeln",
        ["toolCrop"] = "Zuschneiden",
        ["color"] = "Farbe",
        ["blur"] = "Weichzeichner",
        ["size"] = "Größe",
        ["hex"] = "Hex",
        ["ok"] = "OK",
        ["cancel"] = "Abbrechen",
        ["trayTooltip"] = "DM Screenshot",
        ["firstRunTitle"] = "DM Screenshot installiert",
        ["firstRunMessage"] = "Die App ist bereit und läuft im Infobereich. Screenshots über das Tray-Menü oder die Tastenkürzel aufnehmen.",
        // Frame / pretty-background presets (Task 12 — mirror of mac/Sources/DMShot/Localization.swift)
        ["background"] = "Hintergrund",
        ["bgPadding"] = "Abstand",
        ["bgCorners"] = "Ecken",
        ["bgFill"] = "Füllung",
        ["bgPadSmall"] = "Klein",
        ["bgPadMedium"] = "Mittel",
        ["bgPadLarge"] = "Groß",
        ["bgCornerNone"] = "Aus",
        ["bgCornerSoft"] = "Sanft",
        ["bgCornerRound"] = "Rund",
        ["bgBlur"] = "Unschärfe",
        // Verlaufsgrenze + Sammelspeichern
        ["batchSaveHistoryFailed"] = "Speichere die letzten Änderungen erfolgreich im Verlauf, bevor du die Auswahl exportierst.",
        ["historyLimit"] = "Verlaufsgrenze",
        ["historyLimitHelp"] = "Wie viele Aufnahmen der Verlauf behält. Ältere werden automatisch entfernt.",
        ["historyUnlimited"] = "Unbegrenzt",
        ["defaultSaveFolder"] = "Standard-Speicherort",
        ["defaultSaveFolderHelp"] = "Wohin Aufnahmen gespeichert werden. Ist keiner festgelegt, fragt DM Screenshot einmalig und schlägt Bilder\\Screenshots vor.",
        ["chooseFolder"] = "Ordner wählen…",
        ["folderNotSet"] = "Nicht festgelegt",
        ["selectForBatchSave"] = "Zum Speichern auswählen",
        ["saveSelected"] = "Auswahl speichern ({0})",
        ["clearSelection"] = "Auswahl aufheben",
        ["batchSaveFolderTitle"] = "Ordner für die ausgewählten Aufnahmen wählen",
        ["batchSaveDoneTitle"] = "Gespeichert",
        ["batchSaveDone"] = "{0} Aufnahmen gespeichert in:\n{1}",
        ["batchSavePartial"] = "{0} von {1} Aufnahmen konnten nicht gespeichert werden.",
    };
}
